<div class="row">
    <div class="span8">
        &nbsp;
    </div>
</div>
<div class="row registration">
    <div class="span4">
        <?php echo $this->form; ?>

        <p>By clicking Sign Up, you are indicating that you have read 
        and agree to the Terms of Use and Privacy Policy.</p>
    </div>
    <div class="span3">
        <h1>Why you should<br /> sign up:</h1>
        <ul>
            <li>Track your scores</li>
            <li>Compete against other bowlers</li>
            <li>Share scores with friends</li>
            <li>Improve your game</li>
    </div>
</div>