<div class="row">
    <div class="span8">&nbsp;</div>
    <div class="span4">
        <a href="/register"><button class="btn" type="button">Sign Up</button></a>
        <button class="btn" type="button">Login</button>
    </div>
</div>
<div class="row home-left">
    <div class="span4">
        <p><img src="img/pincrowd_logo.png">
        <p class="home-left-text">The first social scoring system that brings<br> bowling to the web.</p>
        <p><img src="img/signup_facebook.png"></p>
        <p><img src="img/signup_twitter.png"></p>        
    </div>
    <div class="span8">
        <div class="home-carousel">
            <img src="img/imac.png">
        </div>
    </div>
</div>
<div class="row">
    <div class="span12 home-footer">
        &nbsp;
    </div>
</div>